# Generated by Django 5.0.8 on 2025-03-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='idbanklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=1000)),
                ('dbms', models.CharField(blank=True, max_length=10)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
    ]
